<?php

/**
 * @file
 * Main module file.
 */

/**
 * Implements hook_views_data_alter().
 */
function eiti_views_extra_views_data_alter(&$data) {
  // We correct the handler, because for some reason, it's messed up.
  if (!empty($data['field_data_field_document_category']['language']['filter'])) {
    $data['field_data_field_document_category']['language']['filter'] = array(
      'handler' => 'eiti_views_handler_filter_field_language',
    );
  }
}

/**
 * Implements hook_form_FORM_ID_alter()
 */
function eiti_views_extra_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#id'] == 'views-exposed-form-documents-search-page') {
    if (isset($form['field_doc_published_date']['#default_value']) && $form['field_doc_published_date']['#default_value'] == '') {
      $form['field_doc_published_date']['#default_value'] = FALSE;
    }

    if (isset($form['field_doc_published_date_1']['#default_value']) && $form['field_doc_published_date_1']['#default_value'] == '') {
      $form['field_doc_published_date_1']['#default_value'] = FALSE;
    }

    if (isset($form_state['input']['field_doc_published_date']) &&  $form_state['input']['field_doc_published_date'] == '') {
      $form_state['input']['field_doc_published_date'] = FALSE;
    }

    if (isset($form_state['input']['field_doc_published_date_1']) && $form_state['input']['field_doc_published_date_1'] == '') {
      $form_state['input']['field_doc_published_date_1'] = FALSE;
    }
  }
}
