# Default vagrant settings file.
#
# You can copy this file to "Vagrantsettings.local.yaml" and configure it.
#

########################################
# Project specific settings.

# VM specific information:
#  - vm_hostonlyip should be unique among your virtual machines.
#  - the VM hostname is created using vm_shortname and vm_environment.
vm_hostonlyip: 10.10.10.49
vm_shortname: eiti
vm_environment: local

# Vhosts and shared folders:
#  - template is the name of the template used to create the vhost.
#  - source points to a folder on the host OS, it can be a relative path.
#  - docroot points to a folder in the gues where source is mounted.
vhosts:
  - domain: eiti-local.dev
    aliases:
      - www.eiti-local.dev
    template: default
    source: ./public_html
    docroot: /var/www/eiti-local
  - domain: eiti-old-local.dev
    aliases:
      - www.eiti-old-local.dev
    template: default
    source: ./old_html
    docroot: /var/www/eiti-old-local


####################
# Database specific settings.

pgsql_allow_remote_access: false
pgsql_root_password: demo3
pgsql_databases:
  - name: eiti_local
    user: eiti_user
    pass: demo1
  - name: eiti_old_local
    user: eiti_old_user
    pass: demo1


########################################
# Vagrant settings.

# Default VM box.
box:
  name: sl6201502
  url: http://user.developmentgateway.org/~wschneider/scientific-6-201502.box
  download_checksum: a73dfd9f73161c32acc0c57f91071e77
  download_checksum_type: md5


########################################
# Puppet settings.
# NOTE: "--parser future" option is required!

# Enable puppet development "mode".
puppet_development: 0

# Default options for the "puppet apply"
puppet_options:
  --parser future
  --verbose

# Development options for the "puppet apply"
puppet_options_dev:
  --parser future
  --verbose
  --debug


####################
# Puppet settings for non-development mode:
puppet_module_name: SchnWalter/happydev
puppet_module_version: 0.2.11

# HACK-ishly remove existing modules and then reinstall.
puppet_force_reinstall: 0

puppet_manifest_file_contents: |
  node default {
    # Dump facts to /tmp/facts.yaml
    # include ::happydev::fairy_dust::debug_helper

    include ::happydev::rhel
    include ::happydev::fairy_dust::orange_blossom

    # include ::happydev::mysql
    include ::happydev::pgsql

    include ::happydev::apache
    include ::happydev::php
  }

####################
# Puppet settings for development mode:

# Relative or absolute path pointing to the local development happy-deployer files.
# NOTE: Do NOT add a trailing slash (/).
happy_deployer_path: ../happy-deployer

# Alternative (development) manifest file, located in the puppet/manifests folder inside happy-deployer:
# Replaces puppet_manifest_file_contents only when in puppet development "mode".
puppet_alternative_manifest_file: dev-eiti.pp
