<?php

include_once 'includes/EITISummaryDataImporter.inc';

/**
 * Implements hook_menu()
 */
function eiti_sdi_menu() {
  $items = array();

  $items['admin/content/summary_data/import'] = array(
    'title' => t('Import Summary data XLSX datasheet'),
    'description' => 'Import Summary data XLSX datasheet',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('eiti_sdi_summary_data_import_form'),
    'access arguments' => array('use summary data import'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'sdi',
  );

  return $items;
}

/**
 * Implements hook_permission()
 */
function eiti_sdi_permission() {
  return array(
    'use summary data import' => array(
      'title' => t('Use Summary data import'),
      'description' => t('Allows to use Summary data import'),
    ),
  );
}

/**
 * Implements Summary data import form
 */
function eiti_sdi_summary_data_import_form($form, &$form_state) {

  $form['file'] = array(
    '#type' => 'managed_file',
    '#title' => t('Summary data'),
    '#description' => t('Allowed extensions: xlsx'),
    '#default_value' => '',
    '#upload_validators' => array(
      'file_validate_extensions' => array('xlsx'),
    ),
    '#upload_location' => 'public://spreadsheets/',
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Import'),
  );

  return $form;
}

/**
 * Implements validation callback for Summary data import form
 */
function eiti_sdi_summary_data_import_form_validate($form, &$form_state) {

}

/**
 * Implements submit callback for Summary data import form
 */
function eiti_sdi_summary_data_import_form_submit($form, &$form_state) {

  $fid = $form_state['values']['file'];
  $file = file_load($fid);

  if ($file) {
    $file->status = FILE_STATUS_PERMANENT;
    file_save($file);
    $file = file_load($file->fid);
    $temp_file = file_copy($file, 'temporary://' . $file->filename, FILE_EXISTS_REPLACE);
  }

  if (isset($file->uri)) {
    $dataImporter = new EITISummaryDataImporter();
    $dataImporter->importSummaryData($temp_file->uri, $file->uri,  $fid);
  }
}

/**
 * Implements hook_block_view_alter()
 */
function eiti_sdi_block_view_alter(&$data, $block) {
  $current_path = current_path();

  if ($current_path == 'summary_data/add') {
    $data['content']['main']['#markup'] = '<dl class="admin-list"><div class="admin-block-item summary_data-add-summary-data">
<dt><a href="/summary_data/add/summary-data">Add Summary data 1.0</a></dt><dd class="description">Summary Data 1.0 was used prior to June 2020.</dd>
<dt><a href="/admin/content/summary_data/import">Add Summary data 2.0</a></dt><dd class="description">Summary data 2.0 is the current data template, launched 1 July 2020. Each file should contain data for a single country, in a single fiscal year.</dd>
</div></dl>';
  }
}
