language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - PATH="$HOME/.config/composer/vendor/bin:$PATH"

# This will create the database
mysql:
  database: drupal
  username: root
  encoding: utf8

install:
  # Grab Drush
  - composer global require "drush/drush:7.*"
  - phpenv rehash
  # Make sure we don't fail when checking out projects
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  # LAMP package installation (mysql is already started)
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm, travis does not support any other method with php and apache
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # Set sendmail so drush doesn't throw an error during site install.
  - echo "sendmail_path='true'" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  # Forward the errors to the syslog so we can print them
  - echo "error_log=syslog" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  # Get latest drupal 8 core
  - cd $TRAVIS_BUILD_DIR/..
  - git clone --depth 1 --branch 7.x http://git.drupal.org/project/drupal.git
  # Make sure the apache root is in our wanted directory
  - cd drupal && export DOCROOT=$(pwd)
  - export APACHE_SITE_CFG="/etc/apache2/sites-available/000-default.conf"
  - sudo sh -c 'cat $TRAVIS_BUILD_DIR/.travis-apache.cfg | sed -e "s,PATH,$DOCROOT,g" | tee > $APACHE_SITE_CFG'

  # Re-enable when trying to get CodeSniffer doesn't return a 403 anymore.
  #- composer global require drupal/coder:\>7

before_script:
  - cd $TRAVIS_BUILD_DIR/../drupal
  # Install the site
  - drush -v site-install minimal --db-url=mysql://root:@localhost/drupal --yes
  - phpenv rehash
  - echo " > MySQL fine-tuning."
  - sudo service mysql stop
  # Increase max_allowed_packet to avoid MySQL errors
  - echo -e "[server]\nmax_allowed_packet=64M" | sudo tee -a /etc/mysql/conf.d/drupal.cnf
  # Performance optimization - MySQL to RAM disk
  - sudo mv /var/lib/mysql /var/run/tmpfs
  - sudo ln -s /var/run/tmpfs /var/lib/mysql
  - sudo service mysql start

  # Restart apache and test it
  - sudo service apache2 restart
  - curl -v "http://localhost"

script:
  # Go to our Drupal module directory
  - mkdir $TRAVIS_BUILD_DIR/../drupal/sites/all/modules/restful
  - cp -R $TRAVIS_BUILD_DIR/* $TRAVIS_BUILD_DIR/../drupal/sites/all/modules/restful/
  # Go to our Drupal main directory
  - cd $TRAVIS_BUILD_DIR/../drupal

  # Download and enable module and its dependencies
  - drush --yes dl ctools
  - drush --yes dl entity_validator --dev
  - drush --yes dl entity
  - drush --yes dl entityreference

  # Patch Entity API.
  - curl -O https://www.drupal.org/files/issues/2086225-entity-access-check-node-create-3.patch
  - patch -p1 $TRAVIS_BUILD_DIR/../drupal/sites/all/modules/entity/modules/callbacks.inc  < 2086225-entity-access-check-node-create-3.patch

  # Enable the RESTful modules
  - drush --yes pm-enable simpletest restful restful_token_auth
  # Run the tests
  - cd $TRAVIS_BUILD_DIR/../drupal
  - php ./scripts/run-tests.sh --php $(which php) --concurrency 4 --verbose --color --url http://localhost RESTful 2>&1 | tee /tmp/simpletest-result.txt
  - egrep -i "([1-9]+ fail)|(Fatal error)|([1-9]+ exception)" /tmp/simpletest-result.txt && exit 1
  - exit 0
