<?php

/**
 * @file
 * Main .module file.
 */

define('MAILCHIMP_SIGNUP_EITI_WIDGET', 1);
define('MAILCHIMP_SIGNUP_EITI_BOTH', 3);

/**
 * Implements hook_form_FORM_ID_alter().
 */
function eiti_mailchimp_form_mailchimp_signup_form_alter(&$form, &$form_state) {
  $signup = $form_state['signup'];

  $mode_defaults = array(
    MAILCHIMP_SIGNUP_BLOCK => array(MAILCHIMP_SIGNUP_BLOCK),
    MAILCHIMP_SIGNUP_PAGE => array(MAILCHIMP_SIGNUP_PAGE),
    MAILCHIMP_SIGNUP_EITI_WIDGET => array(MAILCHIMP_SIGNUP_EITI_WIDGET),
    MAILCHIMP_SIGNUP_EITI_BOTH => array(MAILCHIMP_SIGNUP_EITI_WIDGET, MAILCHIMP_SIGNUP_PAGE),
  );

  unset($form['mode']['#options'][MAILCHIMP_SIGNUP_BLOCK]);
  $form['mode']['#options'][MAILCHIMP_SIGNUP_EITI_WIDGET] = t('EITI Widget');
  $form['mode']['#default_value'] = !empty($signup->mode) ? $mode_defaults[$signup->mode] : array();
}

/**
 * Implements hook_entity_info_alter().
 */
function eiti_mailchimp_entity_info_alter(&$entity_info) {
  $entity_info['mailchimp_signup']['admin ui']['controller class'] = 'EITIMailChimpSignupUIController';
}


/**
 * Implements hook_ctools_plugin_directory().
 *
 * @inheritdoc
 */
function eiti_mailchimp_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
  return NULL;
}

