<?php

/**
 * @file
 * Main .module file, includes all the vital hooks and functions for the module.
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function eiti_ctools_extra_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_libraries_info().
 */
function eiti_ctools_extra_libraries_info() {
  $libraries = array();

  $libraries['eiti-maps'] = array(
    'title' => 'EITI-Maps',
    'version' => '1.0',
    'files' => array(
      'js' => array(
        'mapWidgets.js',
      ),
      'css' => array(
        'main.css',
      ),
    ),
  );

  return $libraries;
}
