<?php
/**
 * @file
 * Define theme helper functions.
 *
 * @TODO: When the theme is finished switch to a custom and small version of modernizr.
 */

/**
 * Default icon for main menu items and the variable name prefix used to store icons.
 */
define('HELPERTHEME_SVG_ICON_NAME_PREFIX', 'helpertheme_svg_icon_');

include_once 'helpertheme.extra.inc';
include_once 'helpertheme.forms.inc';
include_once 'helpertheme.themeoverrides.inc';

/**
 * Implements hook_libraries_info().
 *
 * @TODO: Use different library variants for development and production.
 *
 * @return array
 */
function helpertheme_libraries_info() {
  $libraries['modernizr'] = array(
    'name' => 'Modernizr (custom build)',
    'vendor url' => 'http://modernizr.com',
    'download url' => 'http://modernizr.com/download/',
    'version arguments' => array(
      'file' => 'modernizr-custom.js',
      'pattern' => '/var\s*version\s*=\s*["\']?([0-9a-zA-Z\.-]+)["\']?/',
      'lines' => 64,
      'cols' => 64,
    ),
    'files' => array('js' => array('modernizr-custom.js')),
    'variants' => array(
      'minified' => array(
        'files' => array('js' => array('modernizr-custom.min.js')),
      ),
    ),
  );

  $libraries['svg4everybody'] = array(
    'name' => ' SVG for Everybody',
    'vendor url' => 'https://github.com/jonathantneal/svg4everybody',
    'download url' => 'https://github.com/jonathantneal/svg4everybody/archive/master.tar.gz',
    'version arguments' => array(
      'file' => 'VERSION.txt',
      'pattern' => '/([0-9a-zA-Z\.-]+)/',
      'lines' => 1,
      'cols' => 64,
    ),
    'files' => array('js' => array('svg4everybody.js')),
    'variants' => array(
      'minified' => array(
        'files' => array('js' => array('svg4everybody.min.js')),
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_menu().
 *
 * @return array
 */
function helpertheme_menu() {
  $items = array();

  $items['admin/reports/helpertheme'] = array(
    'title' => 'HelperTheme Reports',
    'description' => 'View theme statistics and reports.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access site reports'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/reports/helpertheme/colors'] = array(
    'title' => 'Color Palette',
    'description' => 'Theme color palette demo page.',
    'page callback' => '_helpertheme_color_palette_demo_page',
    'access arguments' => array('access site reports'),
    'file' => 'helpertheme.admin.inc',
  );

  $items['<nolink>'] = array(
    'page callback' => 'drupal_not_found',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['site-map'] = array(
    'title' => 'Site Map',
    'page callback' => 'helpertheme_site_map',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_ctools_plugin_directory().
 *
 * @param string $module
 * @param string $plugin
 * @return string
 */
function helpertheme_ctools_plugin_directory($module, $plugin) {
  if ($module == 'panels' && $plugin == 'layouts') {
    return 'plugins/' . $plugin;
  }

  return NULL;
}

/**
 * Implements hook_ds_layout_info().
 *
 * @return array
 */
function helpertheme_ds_layout_info() {
  $path = drupal_get_path('module', 'helpertheme');

  $layouts = array();

  $layouts['simplelayout'] = array(
    'label' => t('HelperTheme: Simple Layout'),
    'path' => $path . '/dslayouts/simplelayout',
    'regions' => array(
      'main' => t('Main'),
    ),
  );

  $layouts['doublelayout'] = array(
    'label' => t('HelperTheme: Double Layout'),
    'path' => $path . '/dslayouts/doublelayout',
    'regions' => array(
      'above' => t('Above'),
      'left' => t('Left'),
      'right' => t('Right'),
      'below' => t('Below'),
    ),
  );

  $layouts['mobject'] = array(
    'label' => t('HelperTheme: CSS Media Object'),
    'path' => $path . '/dslayouts/mobject',
    'regions' => array(
      'side' => t('Side'),
      'main' => t('Main'),
    ),
  );

  $layouts['mobjectstacked'] = array(
    'label' => t('HelperTheme: CSS Media Object (stacked)'),
    'path' => $path . '/dslayouts/mobjectstacked',
    'regions' => array(
      'above' => t('Above'),
      'side' => t('Side'),
      'main' => t('Main'),
      'below' => t('Below'),
    ),
  );

  $layouts['widelayout'] = array(
    'label' => t('HelperTheme: Wide Layout'),
    'path' => $path . '/dslayouts/widelayout',
    'regions' => array(
      'above' => t('Above'),
      'main' => t('Main'),
      'below' => t('Below'),
    ),
  );

  return $layouts;
}

/**
 * Implementation of hook_html_head_alter().
 *
 * @param array $head_elements
 */
function helpertheme_html_head_alter(&$head_elements) {
  global $theme, $theme_path;

  if ($theme != 'eiti') {
    return;
  }

  // Force IE to always use most recent engine.
  $head_elements['ie_compatible'] = array(
    '#tag' => 'meta',
    '#type' => 'html_tag',
    '#attributes' => array(
      'http-equiv' => 'X-UA-Compatible',
      'content' => 'IE=Edge',
    ),
  );

  /*
   * The viewport meta tag is needed to instruct the mobile devices to keep the viewport.
   * @see: http://mobile.smashingmagazine.com/2013/03/18/retrofit-a-website-to-be-responsive-with-rwd-retrofit/
   */
  $head_elements['mobile_viewport'] = array(
    '#tag' => 'meta',
    '#type' => 'html_tag',
    '#attributes' => array(
      'name' => 'viewport',
      'content' => 'initial-scale=1.0, width=device-width',
    ),
  );

  // Add favicon related header tags.
  if (!theme_get_setting('favicon_path')) {
    module_load_include('inc', 'helpertheme', 'helpertheme.favicons');
    $head_elements['favicons'] = _helpertheme_favicons($theme_path);
  }
}

/**
 * Preprocess variables for html.tpl.php
 *
 * @param array $variables
 */
function helpertheme_preprocess_html(&$variables) {
  global $theme;

  // Get path to the current module.
  $module_path = drupal_get_path('module', 'helpertheme');

  if (!empty($GLOBALS['user']->uid)) {
    if (defined('PROJECT_ENVIRONMENT') && PROJECT_ENVIRONMENT != 'production') {
      $variables['classes_array'][] = drupal_html_class('project-environment--' . PROJECT_ENVIRONMENT);
    }
    drupal_add_css($module_path . '/styles/helpertheme.authenticated.css', array('weight' => 999, 'preprocess' => FALSE));
  }

  $variables['html_attributes']['lang'] = $variables['language']->language;
  $variables['html_attributes']['dir'] = $variables['language']->dir;
  $variables['html_attributes']['xmlns:svg'] = 'http://www.w3.org/2000/svg';
  $variables['html_attributes']['xmlns:xlink'] = 'http://www.w3.org/1999/xlink';

  // Allow modules to add classes.
  $variables['classes_array'] = array_merge($variables['classes_array'], helpertheme_get_html_classes());
}

/**
 * Preprocess variables for page.tpl.php
 *
 * @param array $variables
 */
function helpertheme_preprocess_page(&$variables) {
  global $theme;
  if ($theme != 'eiti') {
    return;
  }

  // Check to see whether or not the page template should be changed.
  if (!empty($_REQUEST['page-template'])) {
    // Only accept simple page template names.
    if (preg_match('/^[a-z0-9_]+$/', $_REQUEST['page-template'])) {
      $variables['theme_hook_suggestion'] = 'page__' . $_REQUEST['page-template'];
    }
  }

  // Tell "Modernizr" that the HTML5 styles should not be inserted.
  // We already have those styles from normalize.css
  drupal_add_js("html5 = { 'shivCSS': false };", 'inline');

  // Load the "Modernizr" JavaScript library.
  libraries_load('modernizr', 'minified');

  // Load the "SVG for Everybody" JavaScript library.
  libraries_load('svg4everybody', 'minified');

  // Get path to the current module.
  $module_path = drupal_get_path('module', 'helpertheme');

  // Set the default js options.
  $js_options = array(
    'group' => JS_DEFAULT,
    'every_page' => TRUE,
    'scope' => 'footer',
    'requires_jquery' => TRUE,
    'defer' => TRUE,
  );

  // Add the helpertheme script.
  drupal_add_js($module_path . '/scripts/helpertheme.js', $js_options);

  // Set the default css options.
  $css_options = array(
    'group' => CSS_SYSTEM,
    'every_page' => TRUE,
    'media' => 'all',
  );

  // Fix Admin UI style.
  drupal_add_css($module_path . '/styles/helpertheme.admin.css', $css_options);

  /*
   * Project specific CSS on all pages (including admin pages).
   */
  drupal_add_css($module_path . '/styles/helpertheme.wysiwyg.css', $css_options);

  /*
   * Load font Using Google Fonts API.
   *
   * @see http://www.google.com/fonts/specimen/Open+Sans
   */
  if (variable_get('helpertheme_load_external_fonts', TRUE)) {
    $font_variants = array(
      '300',
      '300italic',
      '400',
      '400italic',
      '700',
      '700italic',
    );
    $options = array(
      'external' => TRUE,
      'query' => array(
        'family' => 'Open Sans' . ':' . implode(',', $font_variants),
        'subset' => array('latin'),
      ),
    );

    // Get a list of enabled languages.
    $languages = language_list('enabled');
    $enabled_languages = $languages[1];

    // Only load cyrillic and cyrillic extended character sets if the Russian language is enabled.
    if (array_key_exists('ru', $enabled_languages)) {
      $options['query']['subset'][] = 'cyrillic';
      $options['query']['subset'][] = 'cyrillic-ext';
    }

    $options['query']['subset'] = implode(',', $options['query']['subset']);

    global $is_https;
    $url_scheme = ($is_https) ? 'https://' : 'http://';

    $font_url = url($url_scheme . 'fonts.googleapis.com/css', $options);
    drupal_add_css($font_url, $css_options);
  }

  // Allow modules to hide the page title.
  $variables['page_title_visible'] = helpertheme_page_title_get_status();
}

/**
 * Implements hook_theme().
 *
 * @return array
 */
function helpertheme_theme() {
  return array(
    'html_container' => array(
      'file' => 'helpertheme.theme.inc',
      'render element' => 'element',
    ),
    'svg_icon' => array(
      'file' => 'helpertheme.theme.inc',
    ),
    'svg_inline' => array(
      'file' => 'helpertheme.theme.inc',
    ),
    'svg_sprite' => array(
      'file' => 'helpertheme.theme.inc',
    ),
    'header_items' => array(
      'file' => 'helpertheme.theme.inc',
    ),
    'main_footer' => array(
      'file' => 'helpertheme.theme.inc',
      'template' => 'main-footer',
    ),
  );
}

/**
 * Implements hook_element_info().
 */
function helpertheme_element_info() {
  $types['html_container'] = array(
    '#theme_wrappers' => array('html_container'),
    '#process' => array('form_process_container'),
  );
  return $types;
}

/**
 * Implements hook_theme_registry_alter().
 *
 * @param array $theme_registry
 */
function helpertheme_theme_registry_alter(&$theme_registry) {
  // @HACK: Override the theme registry. Might cause issues with other modules.
  $theme_registry['form_element']['function'] = 'helpertheme_theme_form_element';
  $theme_registry['form_element_label']['function'] = 'helpertheme_form_element_label';
  $theme_registry['menu_local_action']['function'] = 'helpertheme_menu_local_action';
}

/**
 * Implements hook_less_variables_alter().
 *
 * @param array $less_variables
 * @param string $system_name
 */
function helpertheme_less_variables_alter(&$less_variables, $system_name) {
  // Get the list of colors for the theme.
  module_load_include('inc', 'helpertheme', 'helpertheme.colors');
  foreach (helpertheme_color_palette() as $group_key => $color_group) {
    foreach (element_children($color_group) as $color_key) {
      $less_variables['@' . $color_key] = $color_group[$color_key]['#value'];

      // Get variants if any.
      if (!empty($color_group[$color_key]['#variants'])) {
        foreach ($color_group[$color_key]['#variants'] as $variant_key => $variant) {
          $less_variables['@' . $variant_key] = $variant['#value'];
        }
      }
    }
  }

  // Add absolute paths for images; including the trailing slash.
  $less_variables['@base_path'] = '"' . base_path() . '"';
  $less_variables['@theme_path'] = '"' . base_path() . $GLOBALS['theme_path'] . '/"';
  $less_variables['@contextual_section_title'] = '"' . t('edit page content/widgets') . '"';
}

/**
 * Returns an array of SVG sprite icons.
 *
 * @TODO: Optimize!!!
 *
 * @param null|string $icon
 * @param array $options
 * @return array|string
 *   A list of HTML markup containing rendered SVG icons or markup for a single
 *   SVG icon.
 */
function helpertheme_get_svg_icons($icon = NULL, $options = array()) {
  $icon_group = 'icons';
  if (isset($options['icon_group'])) {
    $icon_group = $options['icon_group'];
  }

  // Get a list of available icons.
  $available_icons = helpertheme_get_icons_list($icon_group, FALSE);

  if (isset($icon)) {
    if (!array_key_exists($icon, $available_icons)) {
      return '';
    }

    return theme('svg_icon', array('#info' => $available_icons[$icon], '#options' => $options));
  }

  $icons_list = array();
  foreach (array_keys($available_icons) as $icon) {
    $icons_list[$icon] = theme('svg_icon', array('#info' => $available_icons[$icon], '#options' => $options));
  }

  return $icons_list;
}

/**
 * Return Markup for a single SVG icon.
 *
 * @param string $icon
 * @param array $options
 * @return string
 */
function helpertheme_get_svg_icon($icon, $options = array()) {
  if (empty($icon)) {
    return '';
  }

  return helpertheme_get_svg_icons($icon, $options);
}

/**
 * Returns a list of available icons.
 *
 * NOTE: Always run update_sprites.sh when new svg files are added.
 *
 * @param string $group
 * @param bool $sprite_icons_only
 * @return array
 */
function helpertheme_get_icons_list($group, $sprite_icons_only = TRUE) {
  $available_icons = array();

  // Detect helper files.
  $pattern_array = array(
    drupal_get_path('module', 'helpertheme'),
    'sprites',
    $group,
    '*.svg',
  );
  $svg_files = glob(implode(DIRECTORY_SEPARATOR, $pattern_array));

  if (!empty($svg_files)) {
    foreach ($svg_files as $path) {
      $name = basename($path, '.svg');
      $available_icons[$name] = array(
        'in_sprite' => TRUE,
        'group' => $group,
        'name' => $name,
        'path' => $path,
      );
    }
  }

  if (!$sprite_icons_only) {
    // Detect helper files.
    $pattern_array = array(
      drupal_get_path('module', 'helpertheme'),
      'images',
      $group,
      '*.svg',
    );
    $svg_files = glob(implode(DIRECTORY_SEPARATOR, $pattern_array));

    if (!empty($svg_files)) {
      foreach ($svg_files as $path) {
        $name = basename($path, '.svg');
        if (array_key_exists($name, $available_icons)) {
          continue;
        }
        $available_icons[$name] = array(
          'in_sprite' => FALSE,
          'group' => $group,
          'name' => $name,
          'path' => $path,
        );
      }
    }
  }

  return $available_icons;
}

/**
 * Returns whether the current page is the full page view of the passed-in entity.
 *
 * @param string $type
 * @param stdClass $entity
 * @return bool
 */
function helpertheme_entity_is_page($type, $entity) {
  // Ugly but necessary: there is no standardized way to tell if the current
  // page is an entity view page. This information should be injected here in
  // some form by entity-defining modules.
  $entity_types = array(
    'taxonomy_term' => 2,
    'fieldable_panels_pane' => 4,
  );

  $position = 1;
  if (isset($entity_types[$type])) {
    $position = $entity_types[$type];
  }

  $page_object = menu_get_object($type, $position);
  if (empty($page_object)) {
    return FALSE;
  }

  $entity_identifier = entity_id($type, $entity);
  $page_object_identifier = entity_id($type, $page_object);
  return $entity_identifier == $page_object_identifier;
}

/**
 * Implements hook_panels_pre_render().
 *
 * @inheritdoc
 */
function helpertheme_panels_pre_render($panels_display, $renderer) {
  $class = drupal_html_class('page-layout--' . $panels_display->layout);
  helpertheme_set_html_classes($class);
  helpertheme_page_title_set_status(FALSE);
}

/**
 * Implements hook_entity_view_alter().
 *
 * @inheritdoc
 */
function helpertheme_entity_view_alter(&$build, $type) {
  $entity = NULL;
  if (isset($build['#' . $type])) {
    $entity = $build['#' . $type];
  }
  else if ($type == 'taxonomy_term' && isset($build['#term'])) {
    $entity = $build['#term'];

    // @HACK: Hide the title; we have DS.
    helpertheme_page_title_set_status(FALSE);
  }

  if (empty($entity)) {
    return;
  }

  if (!helpertheme_entity_is_page($type, $entity)) {
    return;
  }

  if (!isset($build['#bundle']) || !isset($build['#view_mode'])) {
    return;
  }

  $ds_layout = ds_get_layout($type, $build['#bundle'], $build['#view_mode']);
  if (isset($ds_layout['layout'])) {
    $class = drupal_html_class('page-layout--' . $ds_layout['layout']);
    helpertheme_set_html_classes($class);
    helpertheme_page_title_set_status(FALSE);
  }
}

/**
 * Implements hook_ds_field_theme_functions_info().
 */
function helpertheme_ds_field_theme_functions_info() {
  return array(
    'theme_helpertheme_ds_field_simple' => t('HelperTheme: Simple'),
  );
}

/**
 * Provide simple HTML for the field.
 *
 * @see: theme_ds_field_minimal().
 * @see: theme_ds_field_minimal().
 *
 * @TODO: Improve styling for multi-value fields.
 */
function theme_helpertheme_ds_field_simple($variables) {
  $output = '';
  $config = $variables['ds-config'];
  $classes = isset($config['classes']) ? ' ' . $config['classes'] : '';

  // Add a simple wrapper.
  $output .= '<div class="field field-name-' . strtr($variables['element']['#field_name'], '_', '-') . $classes . '">';

  // Render the label.
  if (!$variables['label_hidden']) {
    $output .= '<div class="label-' . $variables['element']['#label_display'] . '">' . $variables['label'];
    if (!isset($config['lb-col'])) {
      $output .= ':&nbsp;';
    }
    $output .= '</div>';
  }

  // Render the items.
  $output .= '<div class="field-items">';
  foreach ($variables['items'] as $delta => $item) {
    $output .= '<div class="field-item">' . drupal_render($item) . '</div>';
  }
  $output .= "</div>";

  $output .="</div>";

  return $output;
}

function helpertheme_site_map() {
  $menu_name = 'menu-site-navigation';
  $links = helpertheme_menu_navigation_links($menu_name, 2);

  if (empty($links)) {
    return drupal_not_found();
  }

  $elements['site_navigation'] = array(
    '#type' => 'html_container',
    '#tag' => 'nav',
    '#title' => t('Site Navigation'),
    '#title_tag' => 'h3',
    '#title_attributes' => array(
      'class' => array('section-title', 'element-invisible'),
    ),
    '#contextual_info' => array('admin/structure/menu/manage', array($menu_name)),
    '#attributes' => array(
      'role' => 'navigation',
      'class' => array(
        'site-navigation-wrapper',
      ),
    ),
  );

  $links['#extras']['svgicon_size'] = '1.25em';
  $elements['site_navigation']['links'] = array(
    '#theme' => 'links__enhanced',
    '#links' => $links,
    '#links_prefix' => 'action-link',
    '#attributes' => array(
      'class' => array(
        'navigation-links',
      ),
    ),
  );

  return $elements;
}

/**
 * @param array $elements
 * @param array $image_data
 * @param string $selector_prefix
 * @param bool $with_overlay
 */
function helpertheme_get_background_image_with_overlay(&$elements, $image_data, $selector_prefix, $with_overlay = TRUE) {
  global $theme, $theme_info;
  if ($theme != 'eiti') {
    return;
  }

  // Create the overlay
  if (!isset($elements['overlay']['#type'])) {
    $elements['overlay']['#type'] = 'container';
  }
  if (!isset($elements['overlay']['#attributes']['class']) || !in_array('overlay-wrapper', $elements['overlay']['#attributes']['class'])) {
    $elements['overlay']['#attributes']['class'][] = 'overlay-wrapper';
  }

  // @small: ((@gen_column_width + @gen_gutter_width) * 8) + 1em;
  // @medium: ((@gen_column_width + @gen_gutter_width) * 12) + 1em;
  // @large: ((@gen_column_width + @gen_gutter_width) * 16) + 1em;
  $col_unit = $theme_info->info['less']['vars']['@gen_column_width'] + $theme_info->info['less']['vars']['@gen_gutter_width'];
  // $breakpoint_small = $col_unit * 8 + 1 . 'em';
  $breakpoint_medium = $col_unit * 12 + 1 . 'em';
  // $breakpoint_large = $col_unit * 16 + 1 . 'em';

  // Prepare Markup.
  $featured_image_fid = $image_data['fid'];
  $selector = drupal_html_id($selector_prefix . '-background-image-' . $featured_image_fid);
  $elements['#attributes']['class'][] = $selector;
  $elements['#attributes']['class'][] = 'with-background-image';

  if ($with_overlay) {
    $elements['#attributes']['class'][] = 'with-overlay';
  }

  // Prepare inline style for: 'Smartphone' and 'Tablet'
  // @see: .xMediumAndDown() in custom-responsive.less
  $style_name = 'bg-normal';
  $featured_image_path = image_style_url($style_name, $image_data['uri']);
  $background_image = 'background-image: url("' . $featured_image_path . '");';
  $inline_style_xMediumAndDown = "@media (max-width: $breakpoint_medium) { .${selector} { ${background_image} }}\n";

  // Prepare inline style for: 'Normal Desktop' and 'Large Desktop'.
  // @see: .xNormalAndUp() in custom-responsive.less
  $style_name = 'bg-large';
  if (isset($image_data['width']) && (int) $image_data['width'] < 1920) {
    $style_name = 'bg-enlarged';
  }
  $featured_image_path = image_style_url($style_name, $image_data['uri']);
  $background_image = 'background-image: url("' . $featured_image_path . '");';
  $inline_style_xNormalAndUp = "@media (min-width: $breakpoint_medium) { .${selector} { ${background_image} }}\n";

  $elements['style'] = array(
    '#type' => 'html_tag',
    '#tag' => 'style',
    '#value' => $inline_style_xMediumAndDown . $inline_style_xNormalAndUp,
  );
}
