<?php
/**
 * @file
 * Exposes a custom entity to store score_req.
 */

/**
 * Define administrative URLs.
 */
define('EITIENTITY_SCORE_REQ_UI_PATH', 'score_req');
define('EITIENTITY_SCORE_REQ_ADMIN_UI_PATH', 'admin/structure/score_req/list');
define('EITIENTITY_SCORE_REQ_BUNDLE_ADMIN_UI_PATH', 'admin/structure/score_req');


/**
 * Implements hook_entity_info().
 */
function eitientity_score_req_entity_info() {
  $entity_info = array();

  $menu_wildcard = '%score_req';
  $entity_info['score_req'] = array(
    'label' => t('Score Requirement'),
    'plural label' => t('Score Requirement'),
    'description' => t('A score requirement...'),

    'base table' => 'eiti_score_req',
    'module' => 'eitientity_score_req',

    'entity class' => 'ScoreReqEntity',
    'controller class' => 'EntityAPIController',

    'static cache' => TRUE,
    'fieldable' => TRUE,

    'access callback' => 'eitientity_score_req_access',
    'uri callback' => 'entity_class_uri',

    'entity keys' => array(
      'id' => 'id',
      'bundle' => 'type',
      'label' => 'name',
    ),

    'bundles' => array(),
    'bundle keys' => array(
      'bundle' => 'type',
    ),
    'bundles callback' => 'eitientity_score_req_get_types',

    'admin ui' => array(
      'path' => EITIENTITY_SCORE_REQ_ADMIN_UI_PATH,
      'entity path' => EITIENTITY_SCORE_REQ_UI_PATH,
      'bundle path' => EITIENTITY_SCORE_REQ_BUNDLE_ADMIN_UI_PATH,
      'controller class' => 'ScoreReqEntityUIController',
      'menu wildcard' => $menu_wildcard,
      'file' => 'eitientity_score_req.admin.inc',
    ),
  );

  foreach ($entity_info['score_req']['bundles callback']() as $type => $bundle_info) {
    $entity_info['score_req']['bundles'][$type] = array(
      'label' => $bundle_info['label'],
      'admin' => array(
        'path' => EITIENTITY_SCORE_REQ_BUNDLE_ADMIN_UI_PATH . '/manage/' . $type,
      ),
    );
  }

  return $entity_info;
}

/**
 * Implements hook_admin_paths().
 */
function eitientity_score_req_admin_paths() {
  $paths = array(
    EITIENTITY_SCORE_REQ_UI_PATH . '/add' => TRUE,
    EITIENTITY_SCORE_REQ_UI_PATH . '/add/*' => TRUE,
//    EITIENTITY_SCORE_REQ_UI_PATH . '/*' => TRUE,
    EITIENTITY_SCORE_REQ_UI_PATH . '/*/edit' => TRUE,
    EITIENTITY_SCORE_REQ_UI_PATH . '/*/usage' => TRUE,
    EITIENTITY_SCORE_REQ_UI_PATH . '/*/delete' => TRUE,
  );

  return $paths;
}

/**
 * Returns a list of score_req types.
 */
function eitientity_score_req_get_types() {
  $items = array();

  $items['standard'] = array(
    'label' => t('Standard'),
    'description' => t('Standard Score Requirement.'),
  );

  return $items;
}

/**
 * Returns the entity type name.
 */
function eitientity_score_req_type_get_name($bundle) {
  $bundles = eitientity_score_req_get_types();
  return (isset($bundles[$bundle]['label'])) ? $bundles[$bundle]['label'] : FALSE;
}

/**
 * Access callback for custom score_req entities.
 *
 * @param $op
 * @param ScoreReqEntity $entity
 * @param stdClass $account
 * @param $entity_type
 *
 * @return boolean
 *   Whether access is allowed or not. If the entity type does not specify any
 *   access information, NULL is returned.
 */
function eitientity_score_req_access($op, $entity = NULL, $account = NULL, $entity_type) {
  $operations = array('administer', 'access overview', 'create', 'view', 'edit', 'update', 'delete');
  if (!in_array($op, $operations, TRUE)) {
    // If the $op was not one of the supported ones, we return access denied.
    return FALSE;
  }

  if ($op == 'view') {
    $allow = FALSE;
    if (user_access("$entity_type entity administer")) {
      $allow = TRUE;
    }
    else if ($entity->status && user_access("$entity_type entity $op")) {
      $allow = TRUE;
    }

    return $allow;
  }

  $op = 'administer';
  if (user_access("$entity_type entity $op")) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Menu loader function: load an identifier from its path.
 *
 * @see entity_object_load()
 *
 * @param $entity_id
 * @param $entity_type
 * @return mixed
 */
function score_req_load($entity_id, $entity_type) {
  return entity_object_load($entity_id, $entity_type);
}
/**
 * Implements hook_permission().
 */
function eitientity_score_req_permission() {
  $perms = array();

  $entity_type = 'score_req';
  $entity_info = entity_get_info($entity_type);

  $operations = array('administer', 'view');
  foreach ($operations as $op) {
    $permission_string = "$entity_type entity $op";
    $action = ucfirst($op);
    $t_args = array('%entity' => $entity_info['plural label']);
    $perms[$permission_string] = array(
      'title' => t("$action %entity", $t_args),
    );

    if ($op == 'administer') {
      $perms[$permission_string]['restrict access'] = TRUE;
    }
  }

  return $perms;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function eitientity_score_req_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link to 'score_req/add' on 'admin/content/score_req' page.
  if ($root_path == EITIENTITY_SCORE_REQ_ADMIN_UI_PATH) {
    $item = menu_get_item(EITIENTITY_SCORE_REQ_UI_PATH . '/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}

/**
 * Gets the page title for the passed operation.
 * @see entity_ui_get_page_title()
 */
function eitientity_score_req_entity_ui_get_page_title($op, $entity_type, $entity = NULL) {
  module_load_include('inc', 'entity', 'includes/entity.ui');

  $label = entity_label($entity_type, $entity);

  // Get the entity information.
  $entity_info = entity_get_info($entity_type);
  $t_args = array(
    '@entity_type_label' => drupal_strtolower($entity_info['label']),
    '%label' => $label,
  );

  switch ($op) {
    case 'view':
      return $label;
    case 'edit':
      return t('Edit @entity_type_label %label', $t_args);
    case 'clone':
      return t('Clone @entity_type_label %label', $t_args);
    case 'revert':
      return t('Revert @entity_type_label %label', $t_args);
    case 'delete':
      return t('Delete @entity_type_label %label', $t_args);
    case 'export':
      return t('Export @entity_type_label %label', $t_args);
  }
  if (isset($entity)) {
    list(, , $bundle) = entity_extract_ids($entity_type, $entity);
  }
  else {
    $bundle = NULL;
  }
  return entity_ui_get_action_title($op, $entity_type, $bundle);
}

/**
 * Returns a list of score_reqs by type.
 *
 * @param string $bundle
 * @return array
 */
function eitientity_score_req_get_by_bundle($bundle) {
  $entities = array();

  // Get a list of domains sorted by weight and name.
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'score_req');
  $query->entityCondition('bundle', $bundle);
  $query->propertyOrderBy('name');
  $results = $query->execute();

  if (!empty($results['score_req'])) {
    $ids = array_keys($results['score_req']);
    $entities = entity_load('score_req', $ids);
  }

  return $entities;
}
