<?php
/**
 * @file
 * Exposes a custom entity to store Organisations.
 */

/**
 * Define administrative URLs.
 */
define('EITIENTITY_ORGANISATION_UI_PATH', 'organisation');
define('EITIENTITY_ORGANISATION_ADMIN_UI_PATH', 'admin/content/organisation');
define('EITIENTITY_ORGANISATION_BUNDLE_ADMIN_UI_PATH', 'admin/structure/organisation');

/**
 * Implements hook_entity_info().
 */
function eitientity_organisation_entity_info() {
  $entity_info = array();

  $menu_wildcard = '%organisation';
  $entity_info['organisation'] = array(
    'label' => t('Organisation'),
    'plural label' => t('Organisations'),
    'description' => t('Organisations...'),

    'base table' => 'eiti_organisation',
    'module' => 'eitientity_organisation',

    'entity class' => 'OrganisationEntity',
    'controller class' => 'EntityAPIController',
    //'i18n controller class' => 'EntityDefaultI18nStringController',

    'static cache' => TRUE,
    'fieldable' => TRUE,

    'access callback' => 'eitientity_organisation_access',
    'uri callback' => 'entity_class_uri',

    'entity keys' => array(
      'id' => 'id',
      //'revision' => 'vid',
      'bundle' => 'type',
      'label' => 'name',
      //'language' => 'language',
    ),

    'bundles' => array(),
    'bundle keys' => array(
      'bundle' => 'type',
    ),
    'bundles callback' => 'eitientity_organisation_get_types',

    'admin ui' => array(
      'path' => EITIENTITY_ORGANISATION_ADMIN_UI_PATH,
      'entity path' => EITIENTITY_ORGANISATION_UI_PATH,
      'bundle path' => EITIENTITY_ORGANISATION_BUNDLE_ADMIN_UI_PATH,
      'controller class' => 'OrganisationEntityUIController',
      'menu wildcard' => $menu_wildcard,
      'file' => 'eitientity_organisation.admin.inc',
    ),

    'view modes' => array(
      //'full' => array(
      //  'label' => t('Full'),
      //  'custom settings' => FALSE,
      //),
    ),
  );

  foreach ($entity_info['organisation']['bundles callback']() as $type => $bundle_info) {
    $entity_info['organisation']['bundles'][$type] = array(
      'label' => $bundle_info['label'],
      'admin' => array(
        'path' => EITIENTITY_ORGANISATION_BUNDLE_ADMIN_UI_PATH . '/manage/' . $type,
      ),
    );
  }

  return $entity_info;
}

/**
 * Implements hook_admin_paths().
 */
function eitientity_organisation_admin_paths() {
  $paths = array(
    EITIENTITY_ORGANISATION_UI_PATH . '/add' => TRUE,
    EITIENTITY_ORGANISATION_UI_PATH . '/add/*' => TRUE,
    //EITIENTITY_ORGANISATION_UI_PATH . '/*' => TRUE,
    EITIENTITY_ORGANISATION_UI_PATH . '/*/edit' => TRUE,
    EITIENTITY_ORGANISATION_UI_PATH . '/*/usage' => TRUE,
    EITIENTITY_ORGANISATION_UI_PATH . '/*/delete' => TRUE,
  );

  return $paths;
}

/**
 * Returns a list of organisation types.
 */
function eitientity_organisation_get_types() {
  $items = array();

  $t_args = array('%name' => t('Revenue Stream as Disclosed by Government'));
  $items['agency'] = array(
    'label' => t('Government Agency'),
    'description' => t('Used on summary data %name field.', $t_args),
  );

  $t_args = array('%name' => t('Reconciled Revenue Streams per Company'));
  $items['company'] = array(
    'label' => t('Company'),
    'description' => t('Used on summary data %name field.', $t_args),
  );

  return $items;
}

/**
 * Returns the entity type name.
 */
function eitientity_organisation_type_get_name($bundle) {
  $bundles = eitientity_organisation_get_types();
  return (isset($bundles[$bundle]['label'])) ? $bundles[$bundle]['label'] : FALSE;
}

/**
 * Access callback for custom organisation entities.
 *
 * @param $op
 * @param OrganisationEntity $entity
 * @param stdClass $account
 * @param $entity_type
 *
 * @return boolean
 *   Whether access is allowed or not. If the entity type does not specify any
 *   access information, NULL is returned.
 */
function eitientity_organisation_access($op, $entity = NULL, $account = NULL, $entity_type) {
  $operations = array('administer', 'access overview', 'create', 'view', 'edit', 'update', 'delete');
  if (!in_array($op, $operations, TRUE)) {
    // If the $op was not one of the supported ones, we return access denied.
    return FALSE;
  }

  // Fix for panelizer.
  if ($op == 'update') {
    $op = 'edit';
  }

  if ($op == 'view') {
    $allow = FALSE;
    if (user_access("$entity_type entity administer")) {
      $allow = TRUE;
    }
    else if ($entity->status && user_access("$entity_type entity $op")) {
      $allow = TRUE;
    }

    return $allow;
  }

  if (user_access("$entity_type entity $op")) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Menu loader function: load an identifier from its path.
 *
 * @see entity_object_load()
 *
 * @param $entity_id
 * @param $entity_type
 * @return mixed
 */
function organisation_load($entity_id, $entity_type) {
  return entity_object_load($entity_id, $entity_type);
}
/**
 * Implements hook_permission().
 */
function eitientity_organisation_permission() {
  return _helperentity_entity_type_permission('organisation');
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function eitientity_organisation_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link to 'organisation/add' on 'admin/content/organisation' page.
  if ($root_path == EITIENTITY_ORGANISATION_ADMIN_UI_PATH) {
    $item = menu_get_item(EITIENTITY_ORGANISATION_UI_PATH . '/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}

/**
 * Gets the page title for the passed operation.
 * @see entity_ui_get_page_title()
 */
function eitientity_organisation_entity_ui_get_page_title($op, $entity_type, $entity = NULL) {
  module_load_include('inc', 'entity', 'includes/entity.ui');

  $label = entity_label($entity_type, $entity);

  // Get the entity information.
  $entity_info = entity_get_info($entity_type);
  $t_args = array(
    '@entity_type_label' => drupal_strtolower($entity_info['label']),
    '%label' => $label,
  );

  switch ($op) {
    case 'view':
      return $label;
    case 'edit':
      return t('Edit @entity_type_label %label', $t_args);
    case 'clone':
      return t('Clone @entity_type_label %label', $t_args);
    case 'revert':
      return t('Revert @entity_type_label %label', $t_args);
    case 'delete':
      return t('Delete @entity_type_label %label', $t_args);
    case 'export':
      return t('Export @entity_type_label %label', $t_args);
  }
  if (isset($entity)) {
    list(, , $bundle) = entity_extract_ids($entity_type, $entity);
  }
  else {
    $bundle = NULL;
  }
  return entity_ui_get_action_title($op, $entity_type, $bundle);
}

/**
 * Helper function that returns existing organisation by looking up
 * its name.
 *
 * @param string $name
 *   Name of the organisation.
 *
 * @return bool|array
 *   Loaded entities if found or FALSE.
 */
function eitientity_organisation_lookup_by_name($name) {
  $efq = new EntityFieldQuery();
  $efq_results = $efq->entityCondition('entity_type', 'organisation')
    ->propertyCondition('name', $name, 'LIKE')
    ->execute();

  if (!empty($efq_results['organisation'])) {
    $ids = array_keys($efq_results['organisation']);
    $entities = entity_load('organisation', $ids);
    return $entities;
  }
  return FALSE;
}


/**
 * Implements hook_pathauto().
 */
function eitientity_organisation_pathauto($op) {
  if ($op == 'settings') {
    $settings = array();
    $settings['module'] = 'organisation';
    $settings['token_type'] = 'organisation';
    $settings['groupheader'] = t('Organisation paths');
    $settings['patterndescr'] = t('Default path pattern (applies to all entities with blank patterns below)');
    $settings['patterndefault'] = '[organisation:name]';
    $settings['batch_update_callback'] = 'eitientity_organisation_pathauto_bulk_update_batch_process';
    $settings['batch_file'] = drupal_get_path('module', 'eitientity_organisation') . '/eitientity_organisation.pathauto.inc';

    $languages = array();
    if (module_exists('locale')) {
      $languages = array(LANGUAGE_NONE => t('language neutral')) + locale_language_list('name');
    }

    foreach (eitientity_organisation_get_types() as $bundle => $bundle_details) {
      if (count($languages)) {
        $settings['patternitems'][$bundle] = t('Default path pattern for Organisations (@bundle_label - applies to all @bundle_label countries with blank patterns below)', array('@bundle_label' => $bundle_details['label']));
        foreach ($languages as $lang_code => $lang_name) {
          $settings['patternitems'][$bundle . '_' . $lang_code] = t('Pattern for all @language - Organisations (@bundle_label) paths', array('@bundle_label' => $bundle_details['label'], '@language' => $lang_name));
        }
      }
    }
    return (object) $settings;
  }
}

/**
 * Implements hook_insert().
 */
function eitientity_organisation_entity_insert($entity, $type) {
  if ($type == 'organisation') {
    eitientity_organisation_pathauto_update($entity, 'insert');
  }
}

/**
 * Implements hook_entity_update().
 */
function eitientity_organisation_entity_update($entity, $type) {
  if ($type == 'organisation') {
    eitientity_organisation_pathauto_update($entity, 'update');
  }
}

/**
 * Implements hook_entity_delete().
 */
function eitientity_organisation_entity_delete($entity, $type) {
  if ($type == 'organisation') {
    pathauto_entity_path_delete_all('organisation', $entity, "organisation/{$entity->nid}");
  }
}

/**
 * Helper function that actually creates / updates the path-auto url.
 */
function eitientity_organisation_pathauto_update($entity, $op, array $options = array()) {
  $options += array('language' => pathauto_entity_language('organisation', $entity));

  // Make sure our class is here.
  if (!$entity instanceof OrganisationEntity) {
    $entity = new OrganisationEntity((array) $entity, 'organisation');
  }

  // Skip processing if the node has no pattern.
  if (!pathauto_pattern_load_by_entity('organisation', $entity->type, $options['language'])) {
    return FALSE;
  }

  module_load_include('inc', 'pathauto');
  $uri = entity_uri('organisation', $entity);
  return pathauto_create_alias('organisation', $op, $uri['path'], array('organisation' => $entity), $entity->type, $options['language']);
}

/**
 * Function used to update / create URL alias for multiple implementing countries.
 */
function eitientity_organisation_update_alias_multiple(array $ids, $op, array $options = array()) {
  $options += array('message' => FALSE);

  $implementing_countries = entity_load('organisation', $ids);
  foreach ($implementing_countries as $implementing_country) {
    eitientity_organisation_pathauto_update($implementing_country, $op, $options);
  }

  if (!empty($options['message'])) {
    drupal_set_message(format_plural(count($ids), 'Updated URL alias for 1 implementing country.', 'Updated URL aliases for @count implementing countries.'));
  }
}



/**
 * Implements hook_tokens_info().
 */
function eitientity_organisation_token_info() {
  $token_def = array();

  // Generic adopted title (User Picture, Source, etc.).
  $token_def['tokens']['organisation']['type'] = array(
    'name' => t('Organisation Type'),
    'description' => t('Organisation Type (entity  bundle).'),
  );

  return $token_def;
}

/**
 * Implements hook_tokens().
 */
function eitientity_organisation_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();
  $opted_types = array('organisation');
  $opted_tokens = array('type');

  // Only handling organisation tokens.
  if (!in_array($type, $opted_types)) {
    return;
  }

  foreach ($tokens as $name => $original) {
    if (!in_array($name, $opted_tokens)) {
      continue;
    }

    switch ($name) {
      case 'type':
        $organisation = $data['organisation'];
        $replacements[$original] = $organisation->type;
        break;
    }
  }

  return $replacements;
}

