---
- name: Configure LAMP
  hosts: "{{ hosts|default('devel') }}"
  become: true
  become_user: root

  vars_files:
    - ["environments/{{ project_environment|default('local') }}.yml", "environments/sample.yml"]

  tasks:
    - hostname: name={{ hostname }}
      when: hostname is defined

  roles:
    - common
    - httpd_php56
    - postgresql
    - solr
    - memcached
