---
# Default vagrant settings file.
#
# You can copy this file to "Vagrantsettings.local.yml" and configure it.
#
# For more information:
# @see https://github.com/devgateway/happy-deployer
#

# Used to name the VM and set hostname for the GUEST (only if vagrant.hosts_entry is 1).
# TODO: Use `project_environment` to botstrap instances?!?
project_shortname: eiti
project_environment: local

# Vagrant VM only settings.
#  - hostonlyip: should be unique IP among your virtual machines.
#  - hosts_entry: determines if the GUEST hostname is add added to the HOST /etc/hosts file.
vagrant:
  hostonlyip: 10.10.10.49
  hosts_entry: 0

# Define mount points for the VM.
# - source: path in the host that should be mounted in the VM.
# - target: path in the VM where the sources hould be mounted.
# - skip: if this volume should not be mounted; you can configure your IDE to deploy the files.
vagrant_volumes:
  - source: ../
    target: /var/www/eiti-local
    #skip: true

# The type of synced directory. By default this is "vboxsf" which is very slow.
#   - For linux/mac see: https://www.vagrantup.com/docs/synced-folders/nfs.html
#   - For windows see: https://www.vagrantup.com/docs/synced-folders/smb.html
vagrant_volumes_type: nfs  # for linux/mac
#vagrant_volumes_type: smb  # for windows

# Information about the Vagrant box. Any simple SL7 box should work.
# @see: https://github.com/devgateway/happy-deployer
vagrant_box:
  name: sl7201607
  url: http://user.developmentgateway.org/~wschneider/scientific-7-201607.box
  download_checksum: 7bfe7ba403eeeb20d57fdd1c8b400e10
  download_checksum_type: md5

# Define forwarded ports.
#vagrant_mapped_ports:
#  - source: 5432
#    target: 5432
#  - source: 8009
#    target: 8009

# Ansible variables to override.
common__backups_user: vagrant
common__backups_group: users
httpd__User: vagrant
httpd__Group: users
httpd__User_vhosts: vagrant
httpd__Group_vhosts: users
