required_plugins = %w(vagrant-vbguest)

required_plugins.each do |plugin|
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

Vagrant.configure("2") do |config|
  config.vm.box = "sl7201607"
  config.vm.box_url = "http://user.developmentgateway.org/~wschneider/scientific-7-201607.box"
  config.vm.box_download_checksum = "7bfe7ba403eeeb20d57fdd1c8b400e10"
  config.vm.box_download_checksum_type = "md5"

  config.vm.network "private_network", ip: "10.10.10.49"
  config.vm.network "forwarded_port", guest: 80, host: 80

  config.vm.synced_folder "../", "/var/www/eiti-local"

  config.vm.provider :virtualbox do |vb|
    vb.name = "eiti_#{(Time.now.to_f * 1000.0).to_i}"
    vb.cpus = 1
    vb.memory = 2048
    vb.gui = false
  end
end