---
# Default vagrant settings file.
#
# You can copy this file to "VagrantSettings.local.yml" and configure it.
#

# Used to name the VM and set hostname for the GUEST (only if vagrant.hosts_entry is 1).
# TODO: Use `project_environment` to botstrap instances?!?
project_shortname: eiti
project_environment: local

# Vagrant VM only settings.
#  - hostonlyip: should be unique IP among your virtual machines.
#  - hosts_entry: determines if the GUEST hostname is add added to the HOST /etc/hosts file.
vagrant:
  hostonlyip: 10.10.10.49
  hosts_entry: 0

# Define mount points for the VM.
vagrant_volumes:
  - source: ./
    target: /var/www/eiti-local

# Information about the Vagrant box. Any simple SL7 box should work.
# @see: https://github.com/devgateway/happy-deployer
vagrant_box:
  name: sl7201607
  url: http://user.developmentgateway.org/~wschneider/scientific-7-201607.box
  download_checksum: 7bfe7ba403eeeb20d57fdd1c8b400e10
  download_checksum_type: md5

# Ansible variables to override.
common__backups_user: vagrant
common__backups_group: vagrant
httpd__User: vagrant
httpd__Group: vagrant
httpd__User_vhosts: vagrant
httpd__Group_vhosts: vagrant
