version: '3.6'
#ddev-generated
services:
  db:
    container_name: ddev-${DDEV_SITENAME}-db
    
    image: "$DDEV_DBIMAGE"
    
    stop_grace_period: 60s
    volumes:
      - type: "volume"
        source: mariadb-database
        target: "/var/lib/mysql"
        volume:
          nocopy: true
      - type: "bind"
        source: "."
        target: "/mnt/ddev_config"
    restart: "no"
    user: "$DDEV_UID:$DDEV_GID"
    ports:
      - "127.0.0.1:$DDEV_HOST_DB_PORT:3306"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.platform: ddev
      com.ddev.app-type: drupal7
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - COLUMNS=$COLUMNS
      - LINES=$LINES
      - TZ=
    command: "$DDEV_MARIADB_LOCAL_COMMAND"
    healthcheck:
      interval: 5s
      retries: 12
      start_period: 60s
  web:
    container_name: ddev-${DDEV_SITENAME}-web
    
    image: $DDEV_WEBIMAGE
    
    cap_add:
      - SYS_PTRACE
    volumes:
      - type: bind
        source: ../
        target: /var/www/html
        
        consistency: cached
        
      - ".:/mnt/ddev_config:ro"
      - ddev-global-cache:/mnt/ddev-global-cache
      
      - ddev-ssh-agent_socket_dir:/home/.ssh-agent
      

    restart: "no"
    user: "$DDEV_UID:$DDEV_GID"
    links:
      - db:db
    # ports is list of exposed *container* ports
    ports:
      - "127.0.0.1:$DDEV_HOST_WEBSERVER_PORT:80"
      - "127.0.0.1:$DDEV_HOST_HTTPS_PORT:443"
      - "8025"
    environment:
      - DOCROOT=$DDEV_DOCROOT
      - DDEV_PHP_VERSION=$DDEV_PHP_VERSION
      - DDEV_WEBSERVER_TYPE=$DDEV_WEBSERVER_TYPE
      - DDEV_PROJECT_TYPE=$DDEV_PROJECT_TYPE
      - DDEV_ROUTER_HTTP_PORT=$DDEV_ROUTER_HTTP_PORT
      - DDEV_ROUTER_HTTPS_PORT=$DDEV_ROUTER_HTTPS_PORT
      - DDEV_XDEBUG_ENABLED=$DDEV_XDEBUG_ENABLED
      - DOCKER_IP=127.0.0.1
      - HOST_DOCKER_INTERNAL_IP=172.17.0.1
      - DEPLOY_NAME=local
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - COLUMNS=$COLUMNS
      - LINES=$LINES
      - TZ=
      # HTTP_EXPOSE allows for ports accepting HTTP traffic to be accessible from <site>.ddev.site:<port>
      # To expose a container port to a different host port, define the port as hostPort:containerPort
      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025
      # You can optionally expose an HTTPS port option for any ports defined in HTTP_EXPOSE.
      # To expose an HTTPS port, define the port as securePort:containerPort.
      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80
      - SSH_AUTH_SOCK=/home/.ssh-agent/socket
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.platform: ddev
      com.ddev.app-type: drupal7
      com.ddev.approot: $DDEV_APPROOT

    extra_hosts: [ "host.docker.internal:172.17.0.1" ]

    external_links:
    - "ddev-router:eiti-local.ddev.site" 
    
    healthcheck:
      interval: 4s
      retries: 6
      start_period: 10s



  dba:
    container_name: ddev-${DDEV_SITENAME}-dba
    image: $DDEV_DBAIMAGE
    restart: "no"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.platform: ddev
      com.ddev.app-type: drupal7
      com.ddev.approot: $DDEV_APPROOT
    links:
      - db:db
    ports:
      - "80"
    environment:
      - PMA_USER=db
      - PMA_PASSWORD=db
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - TZ=
      # HTTP_EXPOSE allows for ports accepting HTTP traffic to be accessible from <site>.ddev.site:<port>
      - HTTP_EXPOSE=${DDEV_PHPMYADMIN_PORT}:8036
    healthcheck:
      interval: 90s
      timeout: 2s
      retries: 1


networks:
  default:
    external:
      name: ddev_default
volumes:
  mariadb-database:
    name: "${DDEV_SITENAME}-mariadb"
  
  ddev-ssh-agent_socket_dir:
    external: true
  
  ddev-global-cache:
    name: ddev-global-cache
  
  

  